# nav2_params.yaml – minimal parameters for differential-drive robotaxi

amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2  # rotation noise
    alpha2: 0.2  # translation noise
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.05
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: /scan
    update_min_d: 0.2
    update_min_a: 0.2

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      max_vel_x: 0.3
      max_vel_theta: 1.2
      acc_lim_x: 0.5

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: false
    planner_plugins: [GridAStar]
    GridAStar:
      plugin: "nav2_navfn_planner/NavfnPlanner"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      width: 3.0
      height: 3.0
      resolution: 0.05
      footprint: "[[0.1, 0.09], [0.1, -0.09], [-0.1, -0.09], [-0.1, 0.09]]"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05
      footprint: "[[0.1, 0.09], [0.1, -0.09], [-0.1, -0.09], [-0.1, 0.09]]"
      plugins: [static_layer, costmap_filter_layer]

      # Sidewalk mask comes from /sidewalk_mask topic
      costmap_filter_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/sidewalk_mask"
        subscribe_to_updates: false 