name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: humble

      - name: Install additional dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-colcon-common-extensions

      - name: Build and test with colcon
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          rosdep install --from-paths src --ignore-src -r -y
          colcon build --symlink-install --event-handlers console_direct+
          colcon test --event-handlers console_direct+

      - name: Show test results
        if: always()
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          colcon test-result --verbose